<a href="https://colab.research.google.com/github/MehwishSameer/Machine-Learning/blob/main/Gaussian_NB_Genome_Mutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import neighbors,metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from matplotlib import ticker
import seaborn as sns
import warnings

# options
warnings.filterwarnings('ignore')

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')
path = 'gdrive/My Drive/car.data'
data = pd.read_csv(path)
train = pd.read_csv('gdrive/My Drive/train.csv')
test = pd.read_csv('gdrive/My Drive/test.csv')
submission = pd.read_csv('gdrive/My Drive/submission (5).csv')

Mounted at /content/gdrive


In [4]:
sequence=train[['sequence1','sequence2','sequence3','sequence4','sequence5','sequence6','sequence7','sequence8','sequence9']].values
Label=train[['mutation']]

In [5]:
Le = LabelEncoder()
for i in range(len(sequence[0])):
  sequence[:,i] = Le.fit_transform(sequence[:,i])
print(sequence)

[[0 0 0 ... 1 1 0]
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 1 0 ... 0 1 1]
 [1 0 0 ... 2 1 2]
 [0 0 0 ... 1 1 0]]


In [6]:
X_train,X_test,y_train,y_test=train_test_split(sequence,Label,test_size=0.2,random_state=0)
NBModel=GaussianNB()
NBModel.fit(X_train,y_train)

GaussianNB()

In [7]:
y_predicted=NBModel.predict(X_test)
print(y_predicted)

[1 1 0 ... 0 0 0]


In [8]:
accuracy_score(y_test,y_predicted)*100
print(accuracy_score)
####print(metrics.classification_report(y_test,y_predicted))
###print(metrics.confusion_matrix(y_test,y_predicted))

<function accuracy_score at 0x7f69ca91e050>


In [9]:
sequence1=test[['sequence1','sequence2','sequence3','sequence4','sequence5','sequence6','sequence7','sequence8','sequence9']].values
Le = LabelEncoder()
for i in range(len(sequence1[0])):
  sequence1[:,i] = Le.fit_transform(sequence1[:,i])
pred = NBModel.predict_proba(sequence1)[:,1]
y1_test=submission['mutation']
print(pred)
##accuracy_score(y1_test,pred)*100

[5.65465747e-02 2.93979975e-03 1.18181714e-01 ... 1.00000000e+00
 3.12086472e-04 1.77795356e-01]


In [10]:
submission['mutation'] = pred
submission.to_csv('submission.csv', index=False)
from google.colab import files
files.download("submission.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>