<a href="https://colab.research.google.com/github/MehwishSameer/Machine-Learning/blob/main/Kaggle%20Competitions/Logistic_regression_Genome_Mutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors,metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from matplotlib import ticker
import seaborn as sns
import warnings

# options
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
path = 'gdrive/My Drive/car.data'
data = pd.read_csv(path)
train = pd.read_csv('gdrive/My Drive/train.csv')
test = pd.read_csv('gdrive/My Drive/test.csv')
submission = pd.read_csv('gdrive/My Drive/submission (5).csv')

Mounted at /content/gdrive


In [ ]:
sequence=train[['sequence1','sequence2','sequence3','sequence4','sequence5','sequence6','sequence7','sequence8','sequence9']].values
Label=train[['mutation']]

In [ ]:
Le = LabelEncoder()
for i in range(len(sequence[0])):
  sequence[:,i] = Le.fit_transform(sequence[:,i])
print(sequence)

[[0 0 0 ... 1 1 0]
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 1 0 ... 0 1 1]
 [1 0 0 ... 2 1 2]
 [0 0 0 ... 1 1 0]]


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(sequence,Label,test_size=0.2)
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
prediction=log_reg.predict(X_test)

In [ ]:
###confusion_matrix(y_test,prediction)
sequence1=test[['sequence1','sequence2','sequence3','sequence4','sequence5','sequence6','sequence7','sequence8','sequence9']].values
Le = LabelEncoder()
for i in range(len(sequence1[0])):
  sequence1[:,i] = Le.fit_transform(sequence1[:,i])
pred = log_reg.predict_proba(sequence1)[:,1]
print(log_reg.score(X_test, y_test))
###print(log_reg.score(sequence1, pred))
score=0
comp=submission[['mutation']].to_numpy()
for x in range(12):
  if(comp[x]==pred[x]):
    score=score+1
print(score)

0.8216111111111111
[0.05831056]
0.5527371296470133
[3.31254463e-05]
0.10769876244660066
[0.0109642]
0.40023513384700626
[0.01106889]
0.29092849425586453
[3.02625449e-07]
0.03958417501796652
[9.73569016e-05]
0.11393104099175526
[0.99959655]
0.4882859315968684
[0.00272324]
0.10769876244660066
[0.04937209]
0.36927548437197055
[1.45639892e-06]
0.03958417501796652
[0.07411206]
0.31068175829338357
[0.88389]
0.31068175829338357
0


In [ ]:
submission['mutation'] = pred
submission.to_csv('submission.csv', index=False)
from google.colab import files
files.download("submission.csv")