<a href="https://colab.research.google.com/github/MehwishSameer/Machine-Learning/blob/main/Kaggle%20Competitions/SVM_Genome_Mutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors,metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import svm
from matplotlib import ticker
import seaborn as sns
import warnings

# options
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')
path = 'gdrive/My Drive/car.data'
data = pd.read_csv(path)
train = pd.read_csv('gdrive/My Drive/train.csv')
test = pd.read_csv('gdrive/My Drive/test.csv')
submission = pd.read_csv('gdrive/My Drive/submission (5).csv')

Mounted at /content/gdrive


In [3]:
sequence=train[['sequence1','sequence2','sequence3','sequence4','sequence5','sequence6','sequence7','sequence8','sequence9']].values
Label=train[['mutation']]

In [4]:
Le = LabelEncoder()
for i in range(len(sequence[0])):
  sequence[:,i] = Le.fit_transform(sequence[:,i])
print(sequence)

[[0 0 0 ... 1 1 0]
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 1 0 ... 0 1 1]
 [1 0 0 ... 2 1 2]
 [0 0 0 ... 1 1 0]]


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(sequence,Label,test_size=0.2)
model = svm.SVC()
model.fit(X_train,y_train)
predictions1 = model.predict(X_test)
accuracy1 = metrics.accuracy_score(y_test,predictions1)
print(y_test)                                 #actual
print(predictions1)                           #predicted
print(accuracy1)

In [ ]:
sequence1=test[['sequence1','sequence2','sequence3','sequence4','sequence5','sequence6','sequence7','sequence8','sequence9']].values
Le = LabelEncoder()
for i in range(len(sequence1[0])):
  sequence1[:,i] = Le.fit_transform(sequence1[:,i])
pred = model.predict(sequence1)
submission['mutation'] = pred
submission.to_csv('submission.csv', index=False)
from google.colab import files
files.download("submission.csv")